# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-13 20:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='full name')),
                ('phone', models.CharField(help_text='Please include your country code.', max_length=30, verbose_name='phone number')),
                ('email', models.EmailField(max_length=120, verbose_name='email address')),
                ('subject', models.CharField(max_length=120)),
                ('message', models.TextField()),
                ('emaildate', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'managed': True,
            },
        ),
    ]
